name: Build

on:
  pull_request:
    paths:
      - "Dockerfile"
      - "Makefile"
  push:
    branches:
      - main


jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: Build images
        run: make docker-build

      - name: Release
        run: make docker-release
