name: Build

on:
  pull_request:
    paths:
      - "Dockerfile"
      - "Makefile"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        run: make docker-build
        